### PR TITLE
Fix UI 5.0.0 compatibility and tests

### LINKED ISSUE #106: Setup demo database  TypeError: Atk4\Ui\JsCallback::_getProperAction(): Return value must be of type Atk4\Ui\Js\JsExpressionable, array returned
TypeError: Atk4\Ui\JsCallback::_getProperAction(): Return value must be of type Atk4\Ui\Js\JsExpressionable, array returned

### LINKED ISSUE #107: Incompatible to latest atk4/ui develop
`catchRunawayCallbacks` throws error in 
https://github.com/atk4/login/blob/b5e6a4ad5b96975ab1e31408ee636132e2155482/src/Auth.php#L307C40-L307C40

### LINKED ISSUE #108: Compatible with atk4/ui 5?
I can't for the life of me get atk4/login 3.1.0 installed with atk4/ui 5.0.0. It shows last commits were to update to latest atk4/ui version, but 3.1.0 refuses to allow ui/5. Am I missing something?

https://packagist.org/packages/atk4/login shows this as still requiring atk4/ui 3.1.0. Is this not up to date?

### PR DESCRIPTION
**Pull request by DarkSide666**
Fix UI 5.x compatibility and also fix few more bugs.

fix https://github.com/atk4/login/issues/108
fix https://github.com/atk4/login/issues/107
fix https://github.com/atk4/login/issues/106

### CODE REVIEW

File: src/Model/AccessRule.php [hunk 1]
```diff
@@ -18,14 +18,17 @@ class AccessRule extends Model
...
+
     #[\Override]
     protected function init(): void
     {
         parent::init();
 
         /** @var HasOneSql */
         $r = $this->hasOne('role_id', [
-            'model' => [Role::class],
+            'model' => Model::fromSeed($this->_roleModelSeed),
```
Comment (mvorisek) [inline src/Model/AccessRule.php]: do not instantiate here

File: src/Model/AccessRule.php [hunk 2]
```diff
@@ -18,14 +18,17 @@ class AccessRule extends Model
     public $table = 'login_access_rule';
     public $caption = 'Access Rule';
 
+    /** @var array<mixed> Default Role model. */
+    protected array $_roleModelSeed = [Role::class];
```
Comment (mvorisek) [inline src/Model/AccessRule.php]:
```suggestion
    protected array $roleModelSeed = [Role::class];
```

File: tests/AuthTest.php [hunk 3]
```diff
@@ -138,4 +139,29 @@ public function testAuthCustomLoginAndPasswordFieldName(): void
         $this->expectException(\Exception::class);
         $auth->tryLogin('admin', 'admin'); // wrong password field
     }
+
+    public function testCustomUserModel(): void
```
Comment (mvorisek) [inline tests/AuthTest.php:143]: does this test have any purpose?

File: src/Form/Register.php [hunk 4]
```diff
@@ -25,6 +29,12 @@ protected function init(): void
         $this->buttonSave->set('Register');
         $this->buttonSave->addClass('large fluid');
         $this->buttonSave->iconRight = 'right arrow';
+
+        if ($this->linkSuccess !== [null]) {
```
Comment (mvorisek) [inline src/Form/Register.php:33]: this is new, why?

File: composer.json [hunk 5]
```diff
@@ -62,7 +62,8 @@
     },
     "autoload-dev": {
         "psr-4": {
-            "Atk4\\Login\\Tests\\": "tests/"
+            "Atk4\\Login\\Tests\\": "tests/",
+            "Atk4\\Ui\\Tests\\": "vendor/atk4/ui/tests/"
```
Comment (mvorisek) [inline composer.json]: autoload-dev.files[0] might be better to stress the need explicitly

File: tests/AuthTest.php (hunk 3 above)
Comment (DarkSide666) [reply tests/AuthTest.php:143]: I think yes. It shows how you can add custom fields (last_login in this case) in custom user model and test how it works. Also tests after login hook.

File: src/Form/Register.php (hunk 4 above)
Comment (DarkSide666) [reply src/Form/Register.php:33]: Sometimes after new user signup we want to redirect to some page instead of just showing success message and be stuck there. A bit similar like after login - we can redirect somewhere.

File: composer.json [hunk 6]
```diff
@@ -63,7 +63,8 @@
     "autoload-dev": {
         "psr-4": {
             "Atk4\\Login\\Tests\\": "tests/"
-        }
+        },
+        "files": ["vendor/atk4/ui/tests/CreateAppTrait.php"]
```
Comment (mvorisek) [inline composer.json]:
```suggestion
        "files": [
            "vendor/atk4/ui/tests/CreateAppTrait.php"
        ]
```

minor CS

**Comment by DarkSide666** [comment]
Behat test still fails because of some javascript crap, but that's ok. Will fix that in next release.
